### ISSUE TITLE
Little bug in amr.handleBeMode()

### ISSUE THREAD

**Issue by alopumomovia** [hdiniz/rtpdump#1]
`isLastFrame := (rtpFrameHeader[0]&0x08)>>4&0x01 == 0x00` should be instead `isLastFrame := (rtpFrameHeader[0]&0x08)>>3&0x01 == 0x00` 
That is, it should be shifted by 3 positions not by 4.

Also what is the point of &0x01?

Best regards.

**Comment by hdiniz** [comment]
Thanks for letting me know!

You're right about both. It was an oversight in my part.

Best regards!

**Comment by hdiniz** [comment]
662baa2080310f893ff27b8b871bff48a67100c3
